DataFrames

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [4]:
df = pd.DataFrame(data)
print(df)

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [5]:
print(df.head(2))  # first 2 data will provide

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [6]:
print(df.tail(3))  # last 3 data will provide?

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

loc and iloc

In [7]:
print(df.iloc[1:3,0:3]) # rows,cols

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance

In [8]:
print(df.loc[1:2,['Age','Department']])

    Age Department
1  30.0         IT
2  35.0    Finance

In [9]:
#  access only one colume
print(df['Age'])

# multiple columns
print(df[['Age','Name']])

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64
    Age     Name
0  25.0    Alice
1  30.0      Bob
2  35.0  Charlie
3   NaN    David
4  29.0      Eve
5  25.0    Alice

In [10]:
# for just to drop it temporerly
df = pd.DataFrame(data)
print(df)
print(df.drop('Age',axis=1,inplace=False))

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0
      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [11]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [12]:
print(df.shape)

(6, 4)

In [13]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         5 non-null      float64
 2   Department  6 non-null      str
 3   Salary      5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 324.0 bytes
None

In [14]:
print(df.describe())

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

Broadcasting

In [15]:
df['Salary']=df['Salary']+5000
print(df['Salary'])

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

Renaming columns

In [20]:
print(df)
df.rename(columns={"Department":"Dept"},inplace=True)
print(df)

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0
      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [21]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [22]:
# to count the how many present
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [23]:
# add new column
df["promoted salary"]=df["Salary"]*10
print(df)

      Name   Age     Dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

Data Cleaning--> removing null values

In [ ]:
df.isnull().sum()  # checking for null values in data frame and there sum

Name               0
Age                1
Dept               0
Salary             1
promoted salary    1
dtype: int64

In [ ]:
# to get just delete the rows with null value
df.dropna(how="any")  #any row that had any null value

      Name   Age     Dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [28]:
df.dropna(how="all") # if all the values in any row are null then we drop

      Name   Age     Dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [26]:
df

      Name   Age     Dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [ ]:
# filling the null values
df["Age"].fillna(df["Age"].mean())  # the null value is replaced with the mean value

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [33]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [ ]:
# forward fill--> the nan above value is placed in place of null
df["Age"] = df["Age"].ffill()

      Name   Age     Dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David  35.0       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [42]:
# bsckward fill--> fill the null vslue with the lower value
df["Salary"] = df["Salary"].bfill()
print(df)

      Name   Age     Dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David  35.0       IT  67000.0         670000.0
4      Eve  29.0       HR  55000.0              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [44]:
# replace a particular name of the row
df["Name"]=df["Name"].replace("Charlie","Rose")
df

    Name   Age     Dept   Salary  promoted salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David  35.0       IT  67000.0         670000.0
4    Eve  29.0       HR  55000.0              NaN
5  Alice  25.0       HR  55000.0         550000.0

Duplicate Values

In [45]:
df_dup=df[df.duplicated()]
df_dup

    Name   Age Dept   Salary  promoted salary
5  Alice  25.0   HR  55000.0         550000.0

In [47]:
df=df.drop_duplicates()
df

    Name   Age     Dept   Salary  promoted salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David  35.0       IT  67000.0         670000.0
4    Eve  29.0       HR  55000.0              NaN

In [49]:
# invalid values
# lambda--> python

df["promoted salary"] = df["promoted salary"].apply(lambda x:x/10 if x>650000 else x)
df

    Name   Age     Dept   Salary  promoted salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David  35.0       IT  67000.0          67000.0
4    Eve  29.0       HR  55000.0              NaN